app:
    jwt:
        expired-at:
        secret-word:
cloud:
    aws:
        bucket:
            access-key:
            default:
                avatar:
            name:
            path:
            region:
            secret-key:
server:
    port: 5050
spring:
    datasource:
        password:
        url:
        username:
    jpa:
        database-platform:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                show-sql: true
springdoc:
    swagger-ui:
        path: /swagger
