app:
  jwt:
    expired-at: 750
    secret-word:
cloud:
  aws:
    bucket:
      access-key:
      default:
        avatar: https://socialmediaapi.s3.eu-central-1.amazonaws.com/nature.jpeg
      name: socialmediaapi
      path: https://socialmediaapi.s3.eu-central-1.amazonaws.com/
      region: eu-central-1
      secret-key:
server:
  port: 5050
spring:
  datasource:
    password:
    url: jdbc:postgresql://localhost:5432/social_media
    username:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
springdoc:
  swagger-ui:
    path: /swagger
